# Generated by Django 3.1.7 on 2021-03-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_swipe_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='avg_mark',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='latitude',
            field=models.FloatField(default=50.908407),
        ),
        migrations.AddField(
            model_name='card',
            name='longitude',
            field=models.FloatField(default=34.795837),
        ),
        migrations.AddField(
            model_name='card',
            name='photo',
            field=models.ImageField(default='https://eu.ui-avatars.com/api/?name=John+Doe', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='about',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
