# Generated by Django 3.1.7 on 2021-04-18 19:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('city_swipe_app', '0003_card_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='users',
            field=models.ManyToManyField(db_table='users_cards', to=settings.AUTH_USER_MODEL),
        ),
    ]
