# Generated by Django 3.1.7 on 2021-04-18 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city_swipe_app', '0004_auto_20210418_2251'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='card',
            table='Card',
        ),
    ]
