# Generated by Django 3.1.7 on 2021-04-26 18:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('city_swipe_app', '0005_auto_20210418_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='about',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='card',
            name='users',
            field=models.ManyToManyField(blank=True, db_table='users_cards', to=settings.AUTH_USER_MODEL),
        ),
    ]
